### ISSUE TITLE
Manual OpenID configuration is missing required parameter(s)?

### ISSUE THREAD

**Issue by asadsahi** [jaredhanson/passport-paypal-oauth#10]
Hi @jaredhanson ,

 I am just trying to follow [meanjs implementation of paypal openid strategy](https://github.com/meanjs/mean/blob/master/modules/users/server/config/strategies/paypal.js) and getting following error. Even I have provided

```
Error: Manual OpenID configuration is missing required parameter(s) - issuer
   at Strategy.manual (C:\Users\asahi\ngnode-fullstack\node_modules\passport-openidconnect\lib\setup\manual.js:5:35)
   at Strategy.authenticate (C:\Users\asahi\ngnode-fullstack\node_modules\passport-openidconnect\lib\strategy.js:274:10)
   at attempt (C:\Users\asahi\ngnode-fullstack\node_modules\passport\lib\middleware\authenticate.js:348:16)
   at authenticate (C:\Users\asahi\ngnode-fullstack\node_modules\passport\lib\middleware\authenticate.js:349:7)
   at C:\Users\asahi\ngnode-fullstack\src\server\features\users\controllers\user\authentication.js:83:43
   at Layer.handle [as handle_request] (C:\Users\asahi\ngnode-fullstack\node_modules\express\lib\router\layer.js:95:5)
   at next (C:\Users\asahi\ngnode-fullstack\node_modules\express\lib\router\route.js:131:13)
   at Route.dispatch (C:\Users\asahi\ngnode-fullstack\node_modules\express\lib\router\route.js:112:3)
   at Layer.handle [as handle_request] (C:\Users\asahi\ngnode-fullstack\node_modules\express\lib\router\layer.js:95:5)
   at C:\Users\asahi\ngnode-fullstack\node_modules\express\lib\router\index.js:277:22
   at Function.process_params (C:\Users\asahi\ngnode-fullstack\node_modules\express\lib\router\index.js:330:12)
   at next (C:\Users\asahi\ngnode-fullstack\node_modules\express\lib\router\index.js:271:10)
   at initialize (C:\Users\asahi\ngnode-fullstack\node_modules\passport\lib\middleware\initialize.js:53:5)
   at Layer.handle [as handle_request] (C:\Users\asahi\ngnode-fullstack\node_modules\express\lib\router\layer.js:95:5)
   at trim_prefix (C:\Users\asahi\ngnode-fullstack\node_modules\express\lib\router\index.js:312:13)
   at C:\Users\asahi\ngnode-fullstack\node_modules\express\lib\router\index.js:280:7
   at Function.process_params (C:\Users\asahi\ngnode-fullstack\node_modules\express\lib\router\index.js:330:12)
   at next (C:\Users\asahi\ngnode-fullstack\node_modules\express\lib\router\index.js:271:10)
   at logger (C:\Users\asahi\ngnode-fullstack\node_modules\morgan\index.js:144:5)
   at Layer.handle [as handle_request] (C:\Users\asahi\ngnode-fullstack\node_modules\express\lib\router\layer.js:95:5)
   at trim_prefix (C:\Users\asahi\ngnode-fullstack\node_modules\express\lib\router\index.js:312:13)
   at C:\Users\asahi\ngnode-fullstack\node_modules\express\lib\router\index.js:280:7
```

Is there anything missing?

**Comment by HamzaKhait** [comment]
Hello,

I'm Facing the same issue, did you find a solution?

**Comment by asadsahi** [comment]
@HamzaKhait no.

**Comment by HamzaKhait** [comment]
Maybe this answer could help : 
https://github.com/jaredhanson/passport-openidconnect/issues/47
